# Generated by Django 3.1.2 on 2020-11-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crimereport', '0002_auto_20201108_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Post',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
