# Generated by Django 3.1.2 on 2020-11-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crimereport', '0003_profile_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('cases', models.CharField(max_length=6500)),
            ],
        ),
    ]
