# Generated by Django 3.1.2 on 2020-11-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRForm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='Email',
            field=models.EmailField(default='jayant@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
