# Generated by Django 3.1.2 on 2020-12-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRForm', '0003_fir_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Not Updated', 'Not updated')], default='Not Updated', max_length=15),
        ),
    ]
