# Generated by Django 3.1.2 on 2020-10-27 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineCrimeManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcrime',
            name='Description',
            field=models.TextField(max_length=64000000000),
        ),
        migrations.AlterField(
            model_name='reportcrime',
            name='zip',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='policestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineCrimeManagement.reportcrime')),
            ],
        ),
    ]
