# Generated by Django 3.1.2 on 2020-11-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineCrimeManagement', '0002_auto_20201027_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcrime',
            name='Description',
            field=models.TextField(),
        ),
    ]
