# Generated by Django 3.1.2 on 2020-11-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineCrimeManagement', '0003_auto_20201104_1925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='policestation',
        ),
        migrations.DeleteModel(
            name='ReportCrime',
        ),
    ]
